version: '3.8'
services:
    cyllenedb:
        image: mysql:8.0.25
        container_name: tethysdb
        restart: always
        environment:
            MYSQL_DATABASE: 'cyllene'
            MYSQL_USER: 'cyllene'
            MYSQL_PASSWORD: 'cyllene'
            MYSQL_ROOT_PASSWORD: 'threeblindmice'
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d/:ro
            - /opt/apps/cyllenedb:/var/lib/mysql
        ports:
            - 3306:3306
    cylleneui:
        image: cylleneui
        container_name: cylleneui
        ports:
            - 80:8080
        restart: always
        depends_on:
            - cyllenedb
